name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo ndk -t arm64-v8a -t armeabi-v7a -o ../src/jnjlib build --release
    - name: Run tests
      run: cargo test --verbose
